### list developers
GET http://localhost:3000/developers


### get developer
GET http://localhost:3000/developers/dev_hh9O4gRpdtwwIrv3qILKL


### create developer
POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "Reymond",
    "email": "reymond@email.com",
    "dateOfBirth": "1988-09-02"
}


### update developer
PATCH  http://localhost:3000/developers/dev_hh9O4gRpdtwwIrv3qILKL
Content-Type: application/json

{
    "email": "johnd@email.com"
}

### delete developer
DELETE  http://localhost:3000/developers/dev_hh9O4gRpdtwwIrv3qILKL
