### list developers
GET http://localhost:3000/developers


### get developer
GET http://localhost:3000/developers/1


### create developer
POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "John",
    "email": "john@email.com",
    "dateOfBirth": "1991-05-03"
}


### update developer
PATCH  http://localhost:3000/developers/1
Content-Type: application/json

{
    "email": "johnd@email.com"
}

### delete developer
DELETE  http://localhost:3000/developers/1
